#!/usr/bin/env node
/**
 * Regenerate e2e/support/routes.catalog.ts from the Angular route modules.
 * Run: npm run routes:extract   (from the e2e/ folder)
 *
 * Parses every *.route.ts, resolves child paths under their parent prefix, and
 * flags placeholders (under-construction), :param routes, and PermissionGuard.
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..', '..', 'src', 'app', 'componets');

// module file -> parent path prefix ('' = paths already absolute/top-level)
const files = [
  { f: 'home/home.route.ts', parent: '' },
  { f: 'dashboard/dashboard.route.ts', parent: '' },
  { f: 'dashboard2/dashboard2.route.ts', parent: '' },
  { f: 'activity-log/activity-log.route.ts', parent: '' },
  { f: 'Sales/sales.route.ts', parent: 'sales' },
  { f: 'Reports/repors.route.ts', parent: 'reports' },
  { f: 'accounting/accounting.route.ts', parent: 'accounting' },
  { f: 'reseller/reseller.route.ts', parent: 'reseller' },
  { f: 'warehouse/warehouse.route.ts', parent: '' },
  { f: 'workflow/workflow.route.ts', parent: '' },
  { f: 'error/error.route.ts', parent: '' },
];

const results = [];

for (const { f, parent } of files) {
  const full = path.join(ROOT, f);
  if (!fs.existsSync(full)) {
    console.error('MISSING', f);
    continue;
  }
  const src = fs.readFileSync(full, 'utf8');

  const matches = [];
  const re = /path:\s*'([^']*)'/g;
  let mm;
  while ((mm = re.exec(src)) !== null) matches.push({ p: mm[1], start: mm.index, end: re.lastIndex });

  for (let i = 0; i < matches.length; i++) {
    const p = matches[i].p;
    const blockEnd = i + 1 < matches.length ? matches[i + 1].start : src.length;
    const after = src.slice(matches[i].start, blockEnd); // bounded to THIS route only
    const isWrapper = /^\s*,?\s*children\s*:/.test(src.slice(matches[i].end, matches[i].end + 40));
    if (isWrapper || p === '') continue;

    const isUC = /loadComponent:\s*uc\b/.test(after);
    const isPlaceholder = /loadComponent:\s*placeholder\b/.test(after) || /placeholder,?\s*data/.test(after);
    const hasPermGuard = /PermissionGuard/.test(after);
    const permMatch = after.match(/permissions:\s*\[([^\]]*)\]/);
    const perms = permMatch
      ? permMatch[1].split(',').map((s) => s.trim().replace(/['"]/g, '')).filter(Boolean)
      : [];

    const fullPath = parent ? `${parent}/${p}` : p;
    results.push({
      module: parent || f.split('/')[0].toLowerCase(),
      path: '/' + fullPath.replace(/^\/+/, ''),
      isPlaceholder: isUC || isPlaceholder,
      hasParam: p.includes(':'),
      requiresPermission: hasPermGuard,
      permissions: perms,
    });
  }
}

const seen = new Set();
const uniq = results.filter((r) => (seen.has(r.path) ? false : (seen.add(r.path), true)));

const header = `// AUTO-GENERATED by scripts/extract-routes.cjs from the Angular route modules.
// Do not edit by hand — run: npm run routes:extract
// ${uniq.length} navigable routes across all modules.

export interface RouteEntry {
  /** Feature module the route belongs to. */
  module: string;
  /** Absolute app path (Angular router URL). */
  path: string;
  /** True when the route currently loads an 'under construction' placeholder page. */
  isPlaceholder: boolean;
  /** True when the path has a required :param and cannot be visited blindly. */
  hasParam: boolean;
  /** True when a PermissionGuard protects the route. */
  requiresPermission: boolean;
  /** Permission keys required by the guard (empty unless requiresPermission). */
  permissions: string[];
}

export const ROUTES: RouteEntry[] = `;

const footer = `;

/** Routes safe to smoke-test by direct navigation (excludes :param routes). */
export const NAVIGABLE_ROUTES = ROUTES.filter((r) => !r.hasParam);

/** Routes that render a real feature page (exclude placeholders + params). */
export const REAL_PAGE_ROUTES = ROUTES.filter((r) => !r.hasParam && !r.isPlaceholder);

/** Placeholder / under-construction routes. */
export const PLACEHOLDER_ROUTES = ROUTES.filter((r) => r.isPlaceholder);

/** Permission-guarded routes. */
export const GUARDED_ROUTES = ROUTES.filter((r) => r.requiresPermission);

/** Routes with a required path parameter (need a real id to visit). */
export const PARAM_ROUTES = ROUTES.filter((r) => r.hasParam);

export const ROUTES_BY_MODULE: Record<string, RouteEntry[]> = ROUTES.reduce(
  (acc, r) => {
    (acc[r.module] ||= []).push(r);
    return acc;
  },
  {} as Record<string, RouteEntry[]>
);
`;

const out = path.resolve(__dirname, '..', 'support', 'routes.catalog.ts');
fs.writeFileSync(out, header + JSON.stringify(uniq, null, 2) + footer);
console.log(`Wrote ${out} (${uniq.length} routes, ${uniq.filter((r) => r.isPlaceholder).length} placeholders)`);
